databases:
  - name: aquaracine-db
    databaseName: aquaracine
    user: aquaracine
    plan: free

services:
  - type: web
    name: aquaracine
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn aquaracine.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aquaracine-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.7"
